### PR TITLE
changed the database for the test profiles for a smaller one

### PR DESCRIPTION
**Pull request by ctuni**
Github automated tests use the config profiles inside the `conf/` folder: `test_{corall|smarter}_{PE|SE}.config`

By specifying the `kraken2_db` there to be the "small one" ([MinusB](https://benlangmead.github.io/aws-indexes/k2), fetched from `s3://flomics-no-backup/references/Genomes/KrakenDB/` the configuration stated in the default config gets overwritten, and the "small" database is used for Github automated tests instead. Otherwise, the default "big" database is used, so our normal research runs are safe.

### CODE REVIEW

**Comment by ctuni** [comment]
As seen [here](https://github.com/Flomics/rnaseq/actions/runs/7530269445/job/20496269619?pr=71), the tests for this PR are already using the MinusB database; we should see a decrease in the total runtime as well when the tests finish: 
image

**Comment by ctuni** [comment]
Before the change:
image

After the change:
image

**Review by julienlag — COMMENTED** [review]
1. there is a lot of redundancy across all config files. Wouldn't it make sense to move the `kraken_db` param (together with other common parameters) to a more generic config file, for example `master_test.config`?
2. On a sidenote: I think we need to use the configs under nextflow-configs/rnaseq instead, otherwise it's not a realistic test. Is there any argument against this?

**Comment by ctuni** [comment]
I agree with both points! I can change it in this same branch to reduce redundancy across the test profiles.
Regarding the second point, there used to be a "test config" file in the `nextflow-configs` repo, but on the main branch, and we are currently using the `dev` one. I think @lcabus-flomics created those test profiles. I'll investigate how to retrieve files from another repo on this repo tests because the test call looks like this:
```
    steps:
      - uses: actions/checkout@v3
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Run pipeline with test data
        run: |
          # TODO nf-core: You can customize CI pipeline run tests as required
          # (eg. adding multiple test runs with different parameters)
          nextflow run ${GITHUB_WORKSPACE} -profile test_corall_PE,awsbatch
```
It's "easy" to use the repo where the tests are running thanks to the `${GITHUB_WORKSPACE}` variable, but we'll need to check out `nextflow-configs` and call it from there.

**Comment by lcabus-flomics** [comment]
Yes, the test profiles were made before we implemented the whole nextflow-config repo, so now it should be obsolete. It can be called using each of the configs in the nextflow-config repo and indeed, create a master_test.config and for each test select the needed library prep kit.

**Comment by ctuni** [comment]
I'll get to it. I think we should also create a single `params.yml` file for each one of the 4 tests, since `nextflow run` only accepts one `-params-file` flag.

**Comment by ctuni** [comment]
Github actions of `rnaseq` repo are now capable of cloning `nextflow-configs` repo. This was not trivial since `nextflow-configs` is a private repo so I created a pair of SSH keys, added the private key on the actions secrets for `rnaseq` repo and the public one on the deployment keys section of the `nextflow-configs` repo (I followed this [stackoverflow answer](https://stackoverflow.com/questions/57612428/cloning-private-github-repository-within-organisation-in-actions)). 
I'll now go to the `nextflow-configs` repo and reduce the redundancy of test files :)

**Comment by ctuni** [comment]
On second thought:
Creating concatenated files for the params just for the Github actions testing makes maintaining them more difficult and does not solve the redundancy issue, because we then have several files with the same information. So I did not change anything from the `nextflow-configs` repo.

What actions do now is this:
```
- name : Clone nextflow-configs repo dev branch
        run: |
          mkdir -p ~/actions_workspace/src
          cd ~/actions_workspace/src
          ssh-agent sh -c 'echo "${{ secrets.PRIVATE_DEPENDENCY }}" | ssh-add - && git clone git@github.com:Flomics/nextflow-configs.git'
          cd nextflow-configs/
          git checkout dev
          cd rnaseq/
          awk 'NF' Flomics_master_params.yml library_prep_kit/smarter_SE_params.yml references/hg38_gencodev39_params.yml > params.yml
          cd
      - name: Run pipeline with test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_master,test_smarter_SE,awsbatch -c ~/actions_workspace/src/nextflow-configs/rnaseq/Flomics_master.config -c ~/actions_workspace/src/nextflow-configs/rnaseq/library_prep_kit/smarter_SE.config -params-file ~/actions_workspace/src/nextflow-configs/rnaseq/params.yml
```

Clones the repo, concatenates the YAML files to a single one, and nextflow calls them directly. 

I'll clean up the test profiles so they now only reference input files and kraken2 database, since all the other necessary configs and params are now referenced correctly from the `nextflow-configs`. I'll let you know when I think it's ready for review and merge :)

**Comment by ctuni** [comment]
(I'll stop with the spam now) The tests have been completed! In around 1h each, using non-redundant profiles, and using the correct configs and params from `nextflow-configs` as well :)

**Comment by ctuni** [comment]
I think we can merge this

**Review by asolee — APPROVED** [review]

**Comment by ctuni** [comment]
The test failed because the spot instance where STAR was running ran out of space when downloading the index. This is outside the scope of this pull request but we could fix it by following the same strategy of the kraken2 database download. The star index should not be dowloaded by every STAR process like it's done now (it's downloaded once for every sample) but downloaded just once on a previous process, and pass it to the STAR process.

**Comment by ctuni** [comment]
@julienlag I would merge this PR; the tests now won't run until the PRs are approved (tested it with Giovanni a while ago). And they will run with turret. There is something left to do which is to create the "actions technical user"; this needs to be done by bits. Once done, a small change in the tests file will also need to be done but this can be done with a hotfix branch quickly.

**Pull request merged**
